---
title: "R Notebook"
output: html_notebook
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

```{r}
data_directory <- "/Volumes/SANDISK32_2/final_round5"
csv_files <- list.files(path = data_directory, pattern = "\\.csv$", recursive = TRUE, full.names = TRUE)
csv_files <- csv_files[!grepl("/gan/", csv_files)]
csv_files <- csv_files[!grepl("metadata", csv_files)]
print(csv_files)
```


```{r}
# Initialize an empty list to store data frames
print("Depth of the final circuits:")
data_list <- list()

# Loop through each CSV file
for (csv_file in csv_files) {
  # Extract the folder name from the file path
  folder_name <- dirname(csv_file)
  
  # Read the CSV file
  df <- read.csv(csv_file)
  
  # Assuming the column name containing the best actions is 'Best Actions', replace it with your actual column name
  best_actions <- df$`Best.Actions`
  depth <- df$Depth
  
  # Create a data frame with folder name and best actions
  data <- data.frame(folder = folder_name, depth = depth, best_action = best_actions)
  
  print(tail(depth, n=1))
  
  # Store the data frame in the list
  data_list[[folder_name]] <- data
  
}

```


```{r}
combined_data <- data.frame()

# Loop through each element (data frame) in data_list
for (df_name in names(data_list)) {
  # Add a 'File_Name' column to each data frame
  data_list[[df_name]]$File_Name <- df_name
  
  # Bind the current data frame to combined_data
  combined_data <- rbind(combined_data, data_list[[df_name]])
}

# Optional: Reset row names of the combined data frame
rownames(combined_data) <- NULL
```


Maximum depth ever found:
```{r}
max(combined_data$depth)

```

```{r}
combined_data
```











