---
title: "emd evol round 4"
author: "Bianca Massacci"
date: "5/29/2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
```

```{r}
data_directory <- "/Volumes/SANDISK32_2/final_round4"
csv_files <- list.files(path = data_directory, pattern = "\\.csv$", recursive = TRUE, full.names = TRUE)
csv_files <- csv_files[!grepl("/gan/", csv_files)]
csv_files <- csv_files[!grepl("metadata", csv_files)]
print(csv_files)
```


```{r}
# Initialize an empty list to store data frames
print("Depth of the final circuits:")
data_list <- list()

# Loop through each CSV file
for (csv_file in csv_files) {
  # Extract the folder name from the file path
  folder_name <- dirname(csv_file)
  
  # Read the CSV file
  df <- read.csv(csv_file)
  
  # Assuming the column name containing the best actions is 'Best Actions', replace it with your actual column name
  best_actions <- df$`Best.Actions`
  depth <- df$Depth
  emd <- df$`Best.Fitness`
  
  # Create a data frame with folder name and best actions
  data <- data.frame(folder = folder_name, depth = depth, best_action = best_actions, emd = emd)
  
  print(tail(depth, n=1))
  
  # Store the data frame in the list
  data_list[[folder_name]] <- data
  
}

```

```{r}
data3 <- data.frame()

# Loop through each element (data frame) in data_list
for (df_name in names(data_list)) {
  # Add a 'File_Name' column to each data frame
  data_list[[df_name]]$File_Name <- df_name
  
  # Bind the current data frame to combined_data
  data3 <- rbind(data3, data_list[[df_name]])
}

# Optional: Reset row names of the combined data frame
rownames(data3) <- NULL
```

```{r}
data3 <- data3%>%
  mutate(folder = as.character(folder)) %>%
  mutate(folder = sapply(str_split(folder, "/"), `[`, 5)) %>%
  group_by(folder) %>%
  mutate(time = row_number())
```

Add the multiaction probability values

```{r}
ma_table <- data.frame(
  folder = c("24_05_10_09_09_26", "24_05_14_17_09_56", "24_05_15_05_36_10",
             "24_05_16_09_45_14", "24_05_16_09_46_55", "24_05_16_09_48_30",
             "24_05_16_09_49_20", "24_05_16_10_05_24", "24_05_16_10_06_47"),
  multi_action_prob = c(0.10, 0.10, 0.10, 0.20, 0.20, 0.20, 0.30, 0.30, 0.30)
)
ma_table
```


```{r}
data3 <- data3 %>%
  left_join(ma_table, by = "folder") %>%
  mutate(multi_action_prob = factor(multi_action_prob))
```



```{r}
data3
```


```{r}
ggplot(data3, aes(x = time, y = emd, group = folder, color = multi_action_prob)) +
  geom_line(size = 1.5) +
  labs(title = "Line Plot of EMD Values by Folder",
       x = "Time",
       y = "EMD",
       color = "EMD") +
  theme_minimal()
```

```{r}
tmp <- data3 %>%
  mutate(multi_action_prob2 = multi_action_prob)

tmp %>%
  ggplot(aes(x = time, y = emd)) +
  geom_line(data = tmp %>% dplyr::select(-multi_action_prob), aes(group = folder), color = "gray", size = 0.5, alpha = 0.5) +
  geom_line(aes(color = multi_action_prob, group = folder), color = "#69b3a2", size = 1.2) +
  #scale_color_viridis(discrete = TRUE) +
  #theme_ipsum() +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 14),
    panel.grid = element_blank()
  ) +
  ggtitle("A spaghetti chart of EMD values by multi-action-prob") +
  facet_wrap(~multi_action_prob)
```


