---
title: "R Notebook"
output: html_notebook
---

```{r}
library(ggplot2)
library(dplyr)
```


```{r}
# Specify the path to the Excel file
file_path <- "/Users/bmassacci/main_folder/maastricht/academics/quantum_thesis/scripts/EVOL-WGAN-COMPLETE/output/all_results.xlsx"

# Load the data from the first sheet
all_data <- read_excel(file_path, sheet = 1)

# Display the first few rows of the data to check it

data_2 <- all_data %>%
  filter(round == 2)

data_2 <- data_2 %>%
  mutate(tot_qubits = data_qubits + n_ancilla)
```

```{r}
data_2
```

## Analysis with total qubits (ancilla + data)

```{r}
# Calculate mean and standard deviation for each total qubits group
summary_agg_data <- data_2 %>%
  group_by(tot_qubits) %>%
  summarise(mean_fid = mean(fid), sd_fid = sd(fid))

# Create the plot with error bars
agg_plot <- ggplot(summary_agg_data, aes(x = factor(tot_qubits), y = mean_fid)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  geom_errorbar(aes(ymin = mean_fid - sd_fid, ymax = mean_fid + sd_fid), width = 0.2) +
  labs(title = "Average FID by Total Qubits",
       x = "Total Qubits",
       y = "Average FID") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 14),
    axis.title.x = element_text(size = 10),
    axis.title.y = element_text(size = 10),
    axis.text = element_text(size = 8),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 8),
    plot.margin = unit(c(1, 1, 1, 1), "cm")
  )

# Display the plot
print(agg_plot)
```

```{r}
# Create the scatter plot
scatter_plot <- ggplot(data_2, aes(x = factor(tot_qubits), y = fid, color = factor(n_ancilla), shape = factor(data_qubits))) +
  #geom_point() +
  geom_jitter(width = 0.2, height = 0.2, size = 4, alpha = 0.8) +
  labs(title = "FID by Total Qubits",
       x = "Total Qubits",
       y = "FID",
       color = "Number of Ancillas",
       shape = "Number of Data Qubits") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 18), #face = "bold"
    plot.subtitle = element_text(size = 14),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12)
  )

# Display the plot
print(scatter_plot)
```


```{r}
# Create the scatter plot
scatter_plot <- ggplot(data_2, aes(x = factor(tot_qubits), y = fid)) +
  #geom_point(size = 4, alpha = 0.8) +
  geom_jitter(width = 0.1, height = 0.0, size = 4, alpha = 0.9) +
  labs(title = "FID by Total Qubits",
       subtitle = "Experiment Stage 2",
       x = "Total Qubits",
       y = "FID") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 18), #face = "bold"
    plot.subtitle = element_text(size = 14),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12)
  )

# Display the plot
print(scatter_plot)
```




## Analysis with distinction of ancilla and data qubits
```{r}
# Calculate average FID grouped by n_data_qubits and n_ancilla
summary_data <- data_2 %>%
  group_by(data_qubits, n_ancilla) %>%
  summarise(mean_fid = mean(fid),
            sd_fid = sd(fid),
            mean_emd=mean(emd_test_gan),
            sd_emd=sd(emd_test_gan))

summary_data
```



```{r}
# Create the heatmap
heatmap_plot <- ggplot(summary_data, aes(x = factor(data_qubits), y = factor(n_ancilla), fill = mean_fid)) +
  geom_tile() +
  scale_fill_gradient(low = "darkolivegreen2", high = "orangered3") +
  labs(title = "Average FID by Number of Data Qubits and Ancillas",
       subtitle = "Data from stage 2", 
       x = "Data Qubits",
       y = "Ancillas",
       fill = "Average FID") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 18), #face = "bold"
    plot.subtitle = element_text(size = 14),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12)
  )


# Display the heatmap
print(heatmap_plot)
```

```{r}
# Create the heatmap
heatmap_plot <- ggplot(summary_data, aes(x = factor(data_qubits), y = factor(n_ancilla), fill = mean_emd)) +
  geom_tile() +
  scale_fill_gradient(low = "darkolivegreen2", high = "orangered3") +
  labs(title = "Average EMD by Number of Data Qubits and Ancillas",
       subtitle = "Data from stage 2", 
       x = "Data Qubits",
       y = "Ancillas",
       fill = "Average EMD") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 18), #face = "bold"
    plot.subtitle = element_text(size = 14),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12)
  )


# Display the heatmap
print(heatmap_plot)
```



```{r}
# Create the heatmap with annotations for standard deviation
heatmap_plot <- ggplot(summary_data, aes(x = factor(data_qubits), y = factor(n_ancilla), fill = mean_fid)) +
  geom_tile() +
  geom_text(aes(label = round(sd_fid, 2)), color = "black", size = 5) +
  scale_fill_gradient(low = "lightblue", high = "red") +
  labs(title = "Average FID by Number of Data Qubits and Number of Ancillas",
       subtitle = "Standard deviation annotated in each grid element", 
       x = "Number of Data Qubits",
       y = "Number of Ancillas",
       fill = "Average FID") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 18), #face = "bold"
    plot.subtitle = element_text(size = 14),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12)
  )

# Display the plot
print(heatmap_plot)
```



```{r}
# Create the boxplot
ggplot(data_2, aes(x = factor(n_ancilla), y = fid)) +
  geom_boxplot(fill = "darkolivegreen2") +
  labs(title = "Effect of number of ancilla on FID value",
       subtitle = "Data from stage 2",
       x = "Ancilla qubits",
       y = "FID") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 18), #face = "bold"
    plot.subtitle = element_text(size = 14),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12)
  )
```


```{r}
# Create the boxplot
ggplot(data_2, aes(x = factor(n_ancilla), y = emd_test_gan)) +
  geom_boxplot(fill = "darkolivegreen2") +
  labs(title = "Effect of number of ancilla on EMD value",
       subtitle = "Data from stage 2",
       x = "Ancilla qubits",
       y = "EMD") +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 18), #face = "bold"
    plot.subtitle = element_text(size = 14),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12),
    axis.text = element_text(size = 12),
    legend.title = element_text(size = 14),
    legend.text = element_text(size = 12)
  )
```












